---
title: WTBU Radio
timezone: UTC
collections:
  Interview:
    title: Interview
    output: true
    permalink: "/Interviews/:path/"
    layout: interview
  MusicReviews:
    title: Music Reviews
    output: true
    permalink: "/Music_Reviews/:path/"
    layout: music
  posts:
    title: Posts
    output: true
  TheBeat:
    title: The Beat
    output: false
    permalink: "/TheBeat/:path/"
    layout: beat
  TopNine:
    title: Top Nine
    output: true
    permalink: "/Top/:path/"
    layout: nine
  uploads:
    title: Uploads
    output: true
email: wtbuweb@gmail.com
description: |
  Student run radio station at Boston University
baseurl: ''
url: https://wtbu.github.io
twitter_username: jekyllrb
github_username: wtbu
markdown: kramdown
theme: minima
