---
title: WTBU Radio
timezone: UTC
collections:
  Interview:
    title: Interview
    output: true
    permalink: "/Interview/:path/"
    layout: interview
  MusicReviews:
    title: Music Reviews
    output: true
    permalink: "/Music/:path/"
    layout: music
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: wtbuweb@gmail.com
description: |
  Student run radio station at Boston University
baseurl: ''
url: https://wtbu.github.io
twitter_username: jekyllrb
github_username: wtbu
markdown: kramdown
theme: minima
gems:
- octopress-paginate
